[package]
name = "qx-storage"
version = "0.3.1"
edition = "2021"

[dependencies]
qx-core = { path = "../qx-core" }

dirs = "5.0.1"
serde_yaml = "0.9.32"

color-eyre = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
