[workspace]
members = [
    "crates/qx",
    "crates/qx-core",
    "crates/qx-storage",
    "crates/qx-tui",
]
resolver = "2"

[workspace.dependencies]
color-eyre = "0.6.2"
itertools = "0.12.0"
serde = { version = "1.0.195", features = ["derive"] }
tracing = "0.1.40"