[package]
name = "qx-tui"
version = "0.3.1"
edition = "2021"

[dependencies]
qx-core = { path = "../qx-core" }

crossterm = "0.27.0"
ratatui = "0.26.2"

color-eyre = { workspace = true }
itertools = { workspace = true }
